In [20]:
import pandas as pd
import numpy as np
import os

In [21]:
forders = os.listdir('C:/Users/JIN SEONG EUN/Desktop/빅데이터 분석가 과정/갖고놀기/00~22')
print(forders)

['2000_01.csv', '2000_02.csv', '2000_03.csv', '2000_04.csv', '2000_05.csv', '2000_06.csv', '2000_07.csv', '2000_08.csv', '2000_09.csv', '2000_10.csv', '2000_11.csv', '2000_12.csv', '2001_01.csv', '2001_02.csv', '2001_03.csv', '2001_04.csv', '2001_05.csv', '2001_06.csv', '2001_07.csv', '2001_08.csv', '2001_09.csv', '2001_10.csv', '2001_11.csv', '2001_12.csv', '2002_01.csv', '2002_02.csv', '2002_03.csv', '2002_04.csv', '2002_05.csv', '2002_06.csv', '2002_07.csv', '2002_08.csv', '2002_09.csv', '2002_10.csv', '2002_11.csv', '2002_12.csv', '2003_01.csv', '2003_02.csv', '2003_03.csv', '2003_04.csv', '2003_05.csv', '2003_06.csv', '2003_07.csv', '2003_08.csv', '2003_09.csv', '2003_10.csv', '2003_11.csv', '2003_12.csv', '2004_01.csv', '2004_02.csv', '2004_03.csv', '2004_04.csv', '2004_05.csv', '2004_06.csv', '2004_07.csv', '2004_08.csv', '2004_09.csv', '2004_10.csv', '2004_11.csv', '2004_12.csv', '2005_01.csv', '2005_02.csv', '2005_03.csv', '2005_04.csv', '2005_05.csv', '2005_06.csv', '2005_07.csv', '2005_08.csv', '2005_09.csv', '2005_10.csv', '2005_11.csv', '2005_12.csv', '2006_01.csv', '2006_02.csv', '2006_03.csv', '2006_04.csv', '2006_05.csv', '2006_06.csv', '2006_07.csv', '2006_08.csv', '2006_09.csv', '2006_10.csv', '2006_11.csv', '2006_12.csv', '2007_01.csv', '2007_02.csv', '2007_03.csv', '2007_04.csv', '2007_05.csv', '2007_06.csv', '2007_07.csv', '2007_08.csv', '2007_09.csv', '2007_10.csv', '2007_11.csv', '2007_12.csv', '2008_01.csv', '2008_02.csv', '2008_03.csv', '2008_04.csv', '2008_05.csv', '2008_06.csv', '2008_07.csv', '2008_08.csv', '2008_09.csv', '2008_10.csv', '2008_11.csv', '2008_12.csv', '2009_01.csv', '2009_02.csv', '2009_03.csv', '2009_04.csv', '2009_05.csv', '2009_06.csv', '2009_07.csv', '2009_08.csv', '2009_09.csv', '2009_10.csv', '2009_11.csv', '2009_12.csv', '2010_01.csv', '2010_02.csv', '2010_03.csv', '2010_04.csv', '2010_05.csv', '2010_06.csv', '2010_07.csv', '2010_08.csv', '2010_09.csv', '2010_10.csv', '2010_11.csv', '2010_12.csv', '2011_01.csv', '2011_02.csv', '2011_03.csv', '2011_04.csv', '2011_05.csv', '2011_06.csv', '2011_07.csv', '2011_08.csv', '2011_09.csv', '2011_10.csv', '2011_11.csv', '2011_12.csv', '2012_01.csv', '2012_02.csv', '2012_03.csv', '2012_04.csv', '2012_05.csv', '2012_06.csv', '2012_07.csv', '2012_08.csv', '2012_09.csv', '2012_10.csv', '2012_11.csv', '2012_12.csv', '2013_01.csv', '2013_02.csv', '2013_03.csv', '2013_04.csv', '2013_05.csv', '2013_06.csv', '2013_07.csv', '2013_08.csv', '2013_09.csv', '2013_10.csv', '2013_11.csv', '2013_12.csv', '2014_01.csv', '2014_02.csv', '2014_03.csv', '2014_04.csv', '2014_05.csv', '2014_06.csv', '2014_07.csv', '2014_08.csv', '2014_09.csv', '2014_10.csv', '2014_11.csv', '2014_12.csv', '2015_01.csv', '2015_02.csv', '2015_03.csv', '2015_04.csv', '2015_05.csv', '2015_06.csv', '2015_07.csv', '2015_08.csv', '2015_09.csv', '2015_10.csv', '2015_11.csv', '2015_12.csv', '2016_01.csv', '2016_02.csv', '2016_03.csv', '2016_04.csv', '2016_05.csv', '2016_06.csv', '2016_07.csv', '2016_08.csv', '2016_09.csv', '2016_10.csv', '2016_11.csv', '2016_12.csv', '2017_01.csv', '2017_02.csv', '2017_03.csv', '2017_04.csv', '2017_05.csv', '2017_06.csv', '2017_07.csv', '2017_08.csv', '2017_09.csv', '2017_10.csv', '2017_11.csv', '2017_12.csv', '2018_01.csv', '2018_02.csv', '2018_03.csv', '2018_04.csv', '2018_05.csv', '2018_06.csv', '2018_07.csv', '2018_08.csv', '2018_09.csv', '2018_10.csv', '2018_11.csv', '2018_12.csv', '2019_01.csv', '2019_02.csv', '2019_03.csv', '2019_04.csv', '2019_05.csv', '2019_06.csv', '2019_07.csv', '2019_08.csv', '2019_09.csv', '2019_10.csv', '2019_11.csv', '2019_12.csv', '2020_01.csv', '2020_02.csv', '2020_03.csv', '2020_04.csv', '2020_05.csv', '2020_06.csv', '2020_07.csv', '2020_08.csv', '2020_09.csv', '2020_10.csv', '2020_11.csv', '2020_12.csv', '2021_01.csv', '2021_02.csv', '2021_03.csv', '2021_04.csv', '2021_05.csv', '2021_06.csv', '2021_07.csv', '2021_08.csv', '2021_09.csv', '2021_10.csv', '2021_11.csv', '2021_12.csv', '2022_01.csv', '2022_02.csv', '2022_03.csv', '2022_04.csv', '2022_05.csv', '2022_06.csv']

In [22]:
df_all = pd.DataFrame()
for i in range(0,len(forders)):
    if forders[i].split('.')[1] == 'csv':
        file = 'C:/Users/JIN SEONG EUN/Desktop/빅데이터 분석가 과정/갖고놀기/00~22/'+forders[i]
        df= pd.read_csv(file,encoding='utf-8') 
        df_all = pd.concat([df_all, df])

In [23]:
total = df_all

In [9]:
total.to_csv('C:/Users/JIN SEONG EUN/Desktop/빅데이터 분석가 과정/갖고놀기/total_ufo.csv', sep=',', na_rep='NaN')

In [10]:
total = pd.read_csv('C:/Users/JIN SEONG EUN/Desktop/빅데이터 분석가 과정/갖고놀기/file_name.csv')

C:\Users\JIN SEONG EUN\AppData\Local\Temp\ipykernel_18280\2327415648.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  total = pd.read_csv('C:/Users/JIN SEONG EUN/Desktop/빅데이터 분석가 과정/갖고놀기/file_name.csv')

In [14]:
total = total.reset_index(drop= True)

In [24]:
total

,tablescraper-selected-row,tablescraper-selected-row href,tablescraper-selected-row 2,tablescraper-selected-row 3,tablescraper-selected-row 4,tablescraper-selected-row 5,tablescraper-selected-row 6,tablescraper-selected-row 7,tablescraper-selected-row 8,tablescraper-selected-row 9
0,1/31/00 22:21,https://nuforc.org/webreports/reports/011/S118...,Escondido,CA,USA,Circle,8 mins,approx 22:21 saw a bright light hovering just ...,2/16/00,NaN
1,1/31/00 21:00,https://nuforc.org/webreports/reports/058/S585...,Cape Canaveral,FL,USA,Light,1 minute,Glowing green light came up right side of movi...,10/8/07,NaN
2,1/30/00 23:15,https://nuforc.org/webreports/reports/011/S118...,San Francisco (Farallon Island),CA,USA,Triangle,:15,Encountered large triangular object while nigh...,2/16/00,NaN
3,1/30/00 10:30,https://nuforc.org/webreports/reports/011/S118...,New Wilmington,PA,USA,Circle,2 minutes,An airplane like object was witneesed in the s...,2/16/00,NaN
4,1/29/00 13:00,https://nuforc.org/webreports/reports/011/S118...,Beaverton,OR,USA,Cylinder,15min,Traveling from Portland to Beaverton Saturday ...,2/16/00,NaN
...,...,...,...,...,...,...,...,...,...,...
262,6/1/22 03:36,https://nuforc.org/webreports/reports/168/S168...,Dayton,MN,USA,Light,a few seconds,"Pulsing bright blue light flashing across sky,...",6/22/22,NaN
263,6/1/22 03:00,https://nuforc.org/webreports/reports/168/S168...,Shohola,PA,USA,Cylinder,6-8 seconds,Thick white bar of light descends while moving...,6/22/22,Yes
264,6/1/22 01:19,https://nuforc.org/webreports/reports/168/S168...,Dubai,Dubai,United Arab Emirates,Unknown,I am a living human alien,I am a living human alien hybrid,6/22/22,NaN
265,6/1/22 00:01,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z - shaped formation of UFOs,6/22/22,Yes,NaN
266,6/1/22 00:00,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z shape UFO formation,6/22/22,NaN,NaN

In [25]:
total.columns = [ 'date_time','url','city','statecode','country','shape','duration','summary','posted','image']

In [26]:
total

,date_time,url,city,statecode,country,shape,duration,summary,posted,image
0,1/31/00 22:21,https://nuforc.org/webreports/reports/011/S118...,Escondido,CA,USA,Circle,8 mins,approx 22:21 saw a bright light hovering just ...,2/16/00,NaN
1,1/31/00 21:00,https://nuforc.org/webreports/reports/058/S585...,Cape Canaveral,FL,USA,Light,1 minute,Glowing green light came up right side of movi...,10/8/07,NaN
2,1/30/00 23:15,https://nuforc.org/webreports/reports/011/S118...,San Francisco (Farallon Island),CA,USA,Triangle,:15,Encountered large triangular object while nigh...,2/16/00,NaN
3,1/30/00 10:30,https://nuforc.org/webreports/reports/011/S118...,New Wilmington,PA,USA,Circle,2 minutes,An airplane like object was witneesed in the s...,2/16/00,NaN
4,1/29/00 13:00,https://nuforc.org/webreports/reports/011/S118...,Beaverton,OR,USA,Cylinder,15min,Traveling from Portland to Beaverton Saturday ...,2/16/00,NaN
...,...,...,...,...,...,...,...,...,...,...
262,6/1/22 03:36,https://nuforc.org/webreports/reports/168/S168...,Dayton,MN,USA,Light,a few seconds,"Pulsing bright blue light flashing across sky,...",6/22/22,NaN
263,6/1/22 03:00,https://nuforc.org/webreports/reports/168/S168...,Shohola,PA,USA,Cylinder,6-8 seconds,Thick white bar of light descends while moving...,6/22/22,Yes
264,6/1/22 01:19,https://nuforc.org/webreports/reports/168/S168...,Dubai,Dubai,United Arab Emirates,Unknown,I am a living human alien,I am a living human alien hybrid,6/22/22,NaN
265,6/1/22 00:01,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z - shaped formation of UFOs,6/22/22,Yes,NaN
266,6/1/22 00:00,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z shape UFO formation,6/22/22,NaN,NaN

In [27]:
total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119627 entries, 0 to 266
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date_time  119627 non-null  object
 1   url        119625 non-null  object
 2   city       119624 non-null  object
 3   statecode  119611 non-null  object
 4   country    119563 non-null  object
 5   shape      119514 non-null  object
 6   duration   119364 non-null  object
 7   summary    116315 non-null  object
 8   posted     104900 non-null  object
 9   image      475 non-null     object
dtypes: object(10)
memory usage: 10.0+ MB

In [28]:
total['date_time'] = pd.to_datetime(total['date_time'], errors = 'coerce')

In [29]:
total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119627 entries, 0 to 266
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date_time  119625 non-null  datetime64[ns]
 1   url        119625 non-null  object
 2   city       119624 non-null  object
 3   statecode  119611 non-null  object
 4   country    119563 non-null  object
 5   shape      119514 non-null  object
 6   duration   119364 non-null  object
 7   summary    116315 non-null  object
 8   posted     104900 non-null  object
 9   image      475 non-null     object
dtypes: datetime64[ns](1), object(9)
memory usage: 10.0+ MB

In [30]:
total['year'] = total['date_time'].dt.year

In [31]:
total

,date_time,url,city,statecode,country,shape,duration,summary,posted,image,year
0,2000-01-31 22:21:00,https://nuforc.org/webreports/reports/011/S118...,Escondido,CA,USA,Circle,8 mins,approx 22:21 saw a bright light hovering just ...,2/16/00,NaN,2000.0
1,2000-01-31 21:00:00,https://nuforc.org/webreports/reports/058/S585...,Cape Canaveral,FL,USA,Light,1 minute,Glowing green light came up right side of movi...,10/8/07,NaN,2000.0
2,2000-01-30 23:15:00,https://nuforc.org/webreports/reports/011/S118...,San Francisco (Farallon Island),CA,USA,Triangle,:15,Encountered large triangular object while nigh...,2/16/00,NaN,2000.0
3,2000-01-30 10:30:00,https://nuforc.org/webreports/reports/011/S118...,New Wilmington,PA,USA,Circle,2 minutes,An airplane like object was witneesed in the s...,2/16/00,NaN,2000.0
4,2000-01-29 13:00:00,https://nuforc.org/webreports/reports/011/S118...,Beaverton,OR,USA,Cylinder,15min,Traveling from Portland to Beaverton Saturday ...,2/16/00,NaN,2000.0
...,...,...,...,...,...,...,...,...,...,...,...
262,2022-06-01 03:36:00,https://nuforc.org/webreports/reports/168/S168...,Dayton,MN,USA,Light,a few seconds,"Pulsing bright blue light flashing across sky,...",6/22/22,NaN,2022.0
263,2022-06-01 03:00:00,https://nuforc.org/webreports/reports/168/S168...,Shohola,PA,USA,Cylinder,6-8 seconds,Thick white bar of light descends while moving...,6/22/22,Yes,2022.0
264,2022-06-01 01:19:00,https://nuforc.org/webreports/reports/168/S168...,Dubai,Dubai,United Arab Emirates,Unknown,I am a living human alien,I am a living human alien hybrid,6/22/22,NaN,2022.0
265,2022-06-01 00:01:00,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z - shaped formation of UFOs,6/22/22,Yes,NaN,2022.0
266,2022-06-01 00:00:00,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z shape UFO formation,6/22/22,NaN,NaN,2022.0

In [32]:
total['city'] = total['city'].fillna('null')
total['statecode'] = total['statecode'].fillna('null')
total['shape'] = total['shape'].fillna('null')
total['duration'] = total['duration'].fillna(0)
total['summary'] = total['summary'].fillna('null')

In [33]:
total.head()

,date_time,url,city,statecode,country,shape,duration,summary,posted,image,year
0,2000-01-31 22:21:00,https://nuforc.org/webreports/reports/011/S118...,Escondido,CA,USA,Circle,8 mins,approx 22:21 saw a bright light hovering just ...,2/16/00,NaN,2000.0
1,2000-01-31 21:00:00,https://nuforc.org/webreports/reports/058/S585...,Cape Canaveral,FL,USA,Light,1 minute,Glowing green light came up right side of movi...,10/8/07,NaN,2000.0
2,2000-01-30 23:15:00,https://nuforc.org/webreports/reports/011/S118...,San Francisco (Farallon Island),CA,USA,Triangle,:15,Encountered large triangular object while nigh...,2/16/00,NaN,2000.0
3,2000-01-30 10:30:00,https://nuforc.org/webreports/reports/011/S118...,New Wilmington,PA,USA,Circle,2 minutes,An airplane like object was witneesed in the s...,2/16/00,NaN,2000.0
4,2000-01-29 13:00:00,https://nuforc.org/webreports/reports/011/S118...,Beaverton,OR,USA,Cylinder,15min,Traveling from Portland to Beaverton Saturday ...,2/16/00,NaN,2000.0

In [34]:
total.isnull().sum()

date_time         2
url               2
city              0
statecode         0
country          64
shape             0
duration          0
summary           0
posted        14727
image        119152
year              2
dtype: int64

In [35]:
total = total.drop(['posted','image'], axis = 1, inplace = False)

In [36]:
total.isnull().sum()

date_time     2
url           2
city          0
statecode     0
country      64
shape         0
duration      0
summary       0
year          2
dtype: int64

In [37]:
total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119627 entries, 0 to 266
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date_time  119625 non-null  datetime64[ns]
 1   url        119625 non-null  object
 2   city       119627 non-null  object
 3   statecode  119627 non-null  object
 4   country    119563 non-null  object
 5   shape      119627 non-null  object
 6   duration   119627 non-null  object
 7   summary    119627 non-null  object
 8   year       119625 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 9.1+ MB

In [38]:
total['month'] = total['date_time'].dt.month

In [39]:
total

,date_time,url,city,statecode,country,shape,duration,summary,year,month
0,2000-01-31 22:21:00,https://nuforc.org/webreports/reports/011/S118...,Escondido,CA,USA,Circle,8 mins,approx 22:21 saw a bright light hovering just ...,2000.0,1.0
1,2000-01-31 21:00:00,https://nuforc.org/webreports/reports/058/S585...,Cape Canaveral,FL,USA,Light,1 minute,Glowing green light came up right side of movi...,2000.0,1.0
2,2000-01-30 23:15:00,https://nuforc.org/webreports/reports/011/S118...,San Francisco (Farallon Island),CA,USA,Triangle,:15,Encountered large triangular object while nigh...,2000.0,1.0
3,2000-01-30 10:30:00,https://nuforc.org/webreports/reports/011/S118...,New Wilmington,PA,USA,Circle,2 minutes,An airplane like object was witneesed in the s...,2000.0,1.0
4,2000-01-29 13:00:00,https://nuforc.org/webreports/reports/011/S118...,Beaverton,OR,USA,Cylinder,15min,Traveling from Portland to Beaverton Saturday ...,2000.0,1.0
...,...,...,...,...,...,...,...,...,...,...
262,2022-06-01 03:36:00,https://nuforc.org/webreports/reports/168/S168...,Dayton,MN,USA,Light,a few seconds,"Pulsing bright blue light flashing across sky,...",2022.0,6.0
263,2022-06-01 03:00:00,https://nuforc.org/webreports/reports/168/S168...,Shohola,PA,USA,Cylinder,6-8 seconds,Thick white bar of light descends while moving...,2022.0,6.0
264,2022-06-01 01:19:00,https://nuforc.org/webreports/reports/168/S168...,Dubai,Dubai,United Arab Emirates,Unknown,I am a living human alien,I am a living human alien hybrid,2022.0,6.0
265,2022-06-01 00:01:00,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z - shaped formation of UFOs,6/22/22,2022.0,6.0
266,2022-06-01 00:00:00,https://nuforc.org/webreports/reports/168/S168...,Kyiv,Ukraine,Other,1 hour,Z shape UFO formation,6/22/22,2022.0,6.0

In [40]:
total['day'] = total['date_time'].dt.day